### ISSUE TITLE
ridership.py error

### ISSUE THREAD

**Issue by nquisen** [GOLewis-McChord/go_src#4]
Product: Python
Source: Scripts, mastery.py ridership.py
Goal: Run master.py with ridership = True
Error:  I just tried to run master.py with ridership.py set to "True" and get a looped/recurring error message. 
 Description:  I have no idea where to even start on this one.  I copied the messages below.  It just keeps running and producing more of the same message. I tried running master.py with ridership set to 'false' and it worked fine. 

Error Message Produced:
C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\python.exe "P:/CTR-External (6040)/CMAQ12-13 (6085)/go/src/scripts/master.py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\master.py", line 13, in <module>
    process()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 165, in process
    Period.publish()
  File "P:\CTR-External (6040)\CMAQ12-13 (6085)\go\src\scripts\rider\ridership.py", line 111, in publish
    p = mp.Pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 118, in Pool
    context=self.get_context())
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\nquisen\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by mlockwood** [comment]
This is an operating system or software issue with Python's multiprocessing library. I would try a Google search of the freeze_support() error and see what they recommend. Trying searching with keyword anaconda as well because it may have to do with the anaconda installation. Let me know if you need more guidance.

**Comment by nquisen** [comment]
OK, will do, I'll research it Monday morning and let you know.  Thanks

**Comment by nquisen** [comment]
If I interpreted the forums correcty the answer is that windows runs python process at the same time vs linux. So you have to add the if__name__ command before you call any other scripts which allows each one to run independently.  Instead of dealing with that I just ran master.py with ridership to false and then ran ridership.py separately and it seems to have run fine.  On to the other issues.  Thanks
